version: '3.7'

services:
  ansible-debian:
    image: registry.gitlab.com/sultangillani/ansible-docker-debian:latest
    build:
      context: .
    stdin_open: true
    tty: true
    container_name: ansible-debian
