version: '3.7'

services:
  ansible-debian:
    image: registry.gitlab.com/sultangillani/ansible-docker-debian:latest
    build:
      context: .
      cache_from:
        - registry.gitlab.com/sultangillani/ansible-docker-debian:latest
        - docker.io/saltman33/ansible-debian-buster
    stdin_open: true
    tty: true
    container_name: ansible-debian
    volumes:
      - ${PWD}:/etc/ansible/roles/roles_to_test
